export enum TipoNotificacao {
  LEMBRETE_PALPITE = 'LEMBRETE_PALPITE',
  RODADA_ABERTA = 'RODADA_ABERTA',
  RODADA_FECHADA = 'RODADA_FECHADA',
  RESULTADOS_ATUALIZADOS = 'RESULTADOS_ATUALIZADOS',
  RANKING_ATUALIZADO = 'RANKING_ATUALIZADO',
}
